### ISSUE TITLE
Profiler does not work in the default blank page of Chrome

### ISSUE THREAD

**Issue by mayankleoboy** [firefox-devtools/firefox-profiler-for-chrome#2]
My default homepage is blank ( i guess the equivalent of about:blank?) I want to start from a blank tab, start the profiler, and then open my testcase/webpage. But currently, the profiler doesnt work on blank tabs. I get the error message shown in attached screenshot.

So instead I have to first open example.com, start the profiler and then profile my testcase.

Can the profiler work on blank tabs?
![Uploading chrome error.png…]()

**Comment by canova** [comment]
Thanks for filing the issue! Chrome doesn't allow extensions to profile privileged pages unfortunately, and I recently made it easier to detect them and show a popup that explains what's happening but I might have missed this case.

What do you mean exactly by the blank page? Can you maybe open up the devtools console in that page and write `window.location.href` and tell us what it returns?

(also can't see the image, maybe there was an issue while uploading)

**Comment by mayankleoboy** [comment]
<img width="1120" alt="chrome error" src="https://github.com/user-attachments/assets/5754a2ba-fff8-44ab-8996-2ce8597c2c7a">

**Comment by mayankleoboy** [comment]
window.location.href   gives : 'chrome://new-tab-page/'

**Comment by canova** [comment]
Yes, unfortunately this is a limitation set by the Chrome's extension API. It's not allowed to access these privileged pages, usually for security reasons. So we can't do anything here.
